# Generated by Django 6.0.3 on 2026-03-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(choices=[('none', 'No Restriction'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('keto', 'Keto'), ('halal', 'Halal'), ('gluten_free', 'Gluten Free'), ('paleo', 'Paleo')], default='none', max_length=50)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('budget', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('fitness_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('build_muscle', 'Build Muscle')], default='maintain', max_length=50)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=20, null=True)),
                ('daily_calorie_target', models.IntegerField(blank=True, null=True)),
                ('daily_water_intake', models.FloatField(blank=True, help_text='Litres per day', null=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
