# Generated by Django 6.0.3 on 2026-03-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_generation_reset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_generation_reset',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan_generations_this_month',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('central', 'Central'), ('eastern', 'Eastern'), ('volta', 'Volta'), ('oti', 'Oti'), ('northern', 'Northern'), ('savannah', 'Savannah'), ('north_east', 'North East'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('ahafo', 'Ahafo'), ('western_north', 'Western North')], max_length=50, null=True),
        ),
    ]
