# Generated by Django 6.0.3 on 2026-03-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_last_generation_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
