# Generated by Django 6.0.3 on 2026-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_health_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_health_condition',
            field=models.TextField(blank=True, default='', help_text='Any health condition not listed above'),
        ),
    ]
