# Generated by Django 6.0.3 on 2026-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_other_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_allergy',
            field=models.TextField(blank=True, default='', help_text='Any allergy not listed above'),
        ),
    ]
