# Generated by Django 6.0.3 on 2026-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_other_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_generations_count',
            field=models.IntegerField(default=0),
        ),
    ]
