# Generated by Django 6.0.3 on 2026-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_plan_generations_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='generation_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
