# Generated by Django 6.0.3 on 2026-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
