# Generated by Django 6.0.3 on 2026-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealplan_is_saved_mealplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
