# Generated by Django 6.0.3 on 2026-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealplan_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='image_url',
        ),
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
