# Generated by Django 6.0.3 on 2026-03-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_remove_mealplan_image_url_meal_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image_url',
        ),
    ]
