# Generated by Django 6.0.3 on 2026-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_meal_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='portion_guide',
            field=models.TextField(blank=True, default=''),
        ),
    ]
