# Generated by Django 6.0.3 on 2026-03-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meal_portion_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='suggested_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
