# Generated by Django 6.0.3 on 2026-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_meal_suggested_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='is_partial',
            field=models.BooleanField(default=False, help_text='True if this is a 3-day half plan for free tier'),
        ),
    ]
