# Generated by Django 6.0.3 on 2026-03-13 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_mealplan_is_partial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plan_generated', 'Plan Generated'), ('plan_saved', 'Plan Saved'), ('upgrade', 'Upgraded to Premium'), ('cancelled', 'Subscription Cancelled'), ('payment_failed', 'Payment Failed'), ('save_limit', 'Save Limit Reached'), ('weekly_summary', 'Weekly Summary'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
