# Generated by Django 6.0.3 on 2026-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_progress_streak_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('plan_generated', 'Plan Generated'), ('plan_saved', 'Plan Saved'), ('upgrade', 'Upgraded to Premium'), ('cancelled', 'Subscription Cancelled'), ('payment_failed', 'Payment Failed'), ('save_limit', 'Save Limit Reached'), ('weekly_summary', 'Weekly Summary'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='streakrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
